### ISSUE TITLE
iG-Loader

### ISSUE THREAD

**Issue by EdwardNketiah** [HXN2/WeB0x-By-HxN-iG-hxn.ops#1]
Hello, why was the iG Loader extension removed from Firefox。Will it still be updated？

**Comment by S7TN** [comment]
Welcome! As for the Add-on , it was removed due to a violation of rights. For your information, there are rights and a programmer and I were working on it with all force, but I do not know why it was deleted. I will investigate the matter and please contact me on Telegram: he_xn

https://t.me/he_xn

**Comment by EdwardNketiah** [comment]
OK,thanks！

**Comment by S7TN** [comment]
> OK,thanks！

I re-downloaded it under a different name. Just wait for it for a day and it will be available automatically, dear

[**This is Link!**](https://addons.mozilla.org/ar/firefox/addon/hxram-downer/)

https://addons.mozilla.org/ar/firefox/addon/hxram-downer/

https://addons.mozilla.org/ar/firefox/addon/hxram-downer/

https://addons.mozilla.org/ar/firefox/addon/hxram-downer/

**Comment by EdwardNketiah** [comment]
nice...Thank you for your enthusiastic answer

**Comment by S7TN** [comment]
It is now fully available and supports Android devices. Please rate us there, thank you

https://addons.mozilla.org/ar/firefox/addon/hxram-downer/

https://addons.mozilla.org/ar/firefox/addon/hxram-downer/

https://addons.mozilla.org/ar/firefox/addon/hxram-downer/

**Comment by EdwardNketiah** [comment]
I have already reviewed it, but my English is not very good. I am using software translation, please forgive me。。。。Thank you again for your efforts

**Comment by S7TN** [comment]
> I have already reviewed it, but my English is not very good. I am using software translation, please forgive me。。。。Thank you again for your effort

Ur Welcome Sir 🌹🌹
